DROP TABLE IF EXISTS `User`;
CREATE TABLE IF NOT EXISTS `User` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`color`	TEXT NOT NULL UNIQUE,
	`login`	TEXT NOT NULL UNIQUE,
	`passhash`	TEXT NOT NULL
);
DROP TABLE IF EXISTS `Session`;
CREATE TABLE IF NOT EXISTS `Session` (
	`session_id`	TEXT NOT NULL UNIQUE,
	`session_data`	TEXT NOT NULL,
	PRIMARY KEY(`session_id`)
);
DROP TABLE IF EXISTS `Post`;
CREATE TABLE IF NOT EXISTS `Post` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`board_id`	INTEGER NOT NULL,
	`author_id`	INTEGER NOT NULL,
	`text`	TEXT NOT NULL,
	`timestamp`	INTEGER NOT NULL,
	FOREIGN KEY(`board_id`) REFERENCES `Board`(`id`) ON DELETE CASCADE,
	FOREIGN KEY(`author_id`) REFERENCES `User`(`id`) ON DELETE CASCADE
);
DROP TABLE IF EXISTS `Board`;
CREATE TABLE IF NOT EXISTS `Board` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT NOT NULL UNIQUE,
	`shortcut`	TEXT NOT NULL UNIQUE,
	`description`	TEXT NOT NULL
);
